import { TailoringRun } from './types';
import { hashContent } from './hash';

// Mock TailoringRun for Phase 1 static prototype
export const mockTailoringRun: TailoringRun = {
  id: 'mock-run-001',
  createdAt: new Date().toISOString(),
  resumeHash: hashContent('mock-resume'),
  jdHash: hashContent('mock-jd'),
  resume: {
    contact: {
      name: 'Alex Rivera',
      email: 'alex.rivera@email.example',
      phone: '(555) 010-2244',
      location: 'Portland, OR',
      links: ['linkedin.com/in/alexrivera', 'github.com/alexrivera-dev'],
    },
    summary: 'Backend-focused software engineer with 3 years of experience building REST APIs, data pipelines, and cloud-deployed services. Comfortable with Python, TypeScript, SQL, and Docker.',
    skills: ['Python', 'TypeScript', 'Node.js', 'PostgreSQL', 'Redis', 'Docker', 'Git', 'REST APIs', 'unit testing', 'CI/CD'],
    experience: [
      {
        company: 'Northline Analytics',
        title: 'Software Engineer',
        startDate: 'Jan 2022',
        endDate: 'Present',
        location: 'Portland, OR',
        bullets: [
          'Built Python FastAPI services handling 2M+ daily requests with PostgreSQL and Redis caching.',
          'Designed ETL jobs that reduced reporting latency from hours to under 15 minutes.',
          'Collaborated with product and QA to ship features using GitHub Actions CI/CD pipelines.',
          'Wrote unit and integration tests that increased backend coverage from 58% to 81%.',
        ],
      },
      {
        company: 'BrightCart Labs',
        title: 'Junior Backend Developer',
        startDate: 'Jun 2020',
        endDate: 'Dec 2021',
        location: 'Remote',
        bullets: [
          'Implemented REST endpoints in Node.js/Express for an e-commerce admin dashboard.',
          'Optimized SQL queries and added indexes that improved checkout API response times by 30%.',
          'Participated in code reviews and on-call rotation for production incidents.',
        ],
      },
    ],
    projects: [
      {
        name: 'Inventory Sync Tool',
        description: 'Created a Python script and scheduled job to reconcile warehouse CSV exports with PostgreSQL inventory tables.',
        bullets: ['Developed automated reconciliation process', 'Reduced manual inventory errors'],
        technologies: ['Python', 'PostgreSQL', 'CSV'],
      },
    ],
    education: [
      {
        institution: 'State University',
        degree: 'B.S. Computer Science',
        field: 'Computer Science',
        graduationDate: '2020',
      },
    ],
    certifications: [
      {
        name: 'AWS Certified Cloud Practitioner',
        issuer: 'Amazon Web Services',
        date: '2023',
      },
    ],
    rawText: '# Mock resume text...',
  },
  jobDescription: {
    jobTitle: 'Backend Software Engineer',
    company: 'Northline Analytics',
    requiredSkills: ['Python', 'SQL', 'PostgreSQL', 'Docker', 'Git', 'REST APIs'],
    preferredSkills: ['FastAPI', 'Redis', 'TypeScript', 'Node.js', 'AWS', 'CI/CD'],
    responsibilities: [
      'Design and implement RESTful APIs using Python and modern web frameworks.',
      'Build reliable data pipelines and background jobs for reporting and ingestion.',
      'Optimize PostgreSQL queries, schema design, and caching strategies with Redis.',
      'Collaborate with frontend, product, and QA teams in an agile environment.',
      'Participate in code reviews, incident response, and CI/CD improvements.',
      'Write automated tests and contribute to engineering best practices.',
    ],
    qualifications: [
      '2+ years of professional backend development experience.',
      'Strong proficiency in Python and SQL.',
      'Experience with PostgreSQL and production API services.',
      'Familiarity with Docker and cloud deployment workflows.',
      'Understanding of automated testing and version control with Git.',
      'Ability to communicate clearly and work cross-functionally.',
    ],
    tools: ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker', 'Git', 'CI/CD', 'AWS'],
    keywords: ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker', 'REST', 'APIs', 'backend', 'data pipelines', 'CI/CD', 'Git', 'AWS', 'TypeScript'],
    seniorityLevel: 'mid',
    domainSignals: ['analytics', 'data', 'backend'],
    softSkills: ['communication', 'collaboration', 'agile'],
    rawText: '# Mock JD text...',
  },
  originalMatchScore: {
    overallScore: 72,
    skillCoverageScore: 85,
    preferredSkillCoverageScore: 70,
    responsibilityAlignmentScore: 75,
    keywordScore: 80,
    seniorityScore: 65,
    criticalMissingRequirements: ['FastAPI experience', 'AWS cloud deployment'],
    explanation: 'Strong match on core backend skills and experience level. Missing some preferred qualifications like FastAPI and AWS deployment experience.',
    breakdown: [
      { dimension: 'Required Skills', score: 85, evidence: 'Covers Python, SQL, PostgreSQL, Docker, Git, REST APIs' },
      { dimension: 'Preferred Skills', score: 70, evidence: 'Has TypeScript, Node.js, CI/CD; missing FastAPI, Redis, AWS' },
      { dimension: 'Responsibilities', score: 75, evidence: 'Experience with APIs, data pipelines, testing, collaboration' },
      { dimension: 'Keywords', score: 80, evidence: 'Matches Python, PostgreSQL, Docker, Git, CI/CD, TypeScript' },
      { dimension: 'Seniority', score: 65, evidence: '3 years experience vs 2+ required; title alignment good' },
    ],
  },
  tailoredMatchScore: {
    overallScore: 88,
    skillCoverageScore: 90,
    preferredSkillCoverageScore: 85,
    responsibilityAlignmentScore: 88,
    keywordScore: 90,
    seniorityScore: 85,
    criticalMissingRequirements: [],
    explanation: 'Excellent match after tailoring. Bullet rewrites emphasize relevant technologies and impact. All required skills clearly demonstrated.',
    breakdown: [
      { dimension: 'Required Skills', score: 90, evidence: 'Strong emphasis on Python, SQL, PostgreSQL, Docker, Git, REST APIs' },
      { dimension: 'Preferred Skills', score: 85, evidence: 'Highlighted FastAPI, Redis, CI/CD, AWS certification' },
      { dimension: 'Responsibilities', score: 88, evidence: 'Direct mapping to API design, data pipelines, optimization, collaboration' },
      { dimension: 'Keywords', score: 90, evidence: 'All key keywords integrated naturally' },
      { dimension: 'Seniority', score: 85, evidence: '3 years experience with increasing responsibility demonstrated' },
    ],
  },
  tailoredResume: {
    tailoredSummary: 'Backend Software Engineer with 3 years of experience building scalable REST APIs, data pipelines, and cloud-deployed services using Python, FastAPI, PostgreSQL, and Redis. AWS Certified Cloud Practitioner with strong expertise in CI/CD and automated testing.',
    tailoredSkills: ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker', 'Git', 'REST APIs', 'CI/CD', 'AWS', 'TypeScript', 'Node.js', 'SQL'],
    tailoredExperience: [
      {
        company: 'Northline Analytics',
        title: 'Software Engineer',
        startDate: 'Jan 2022',
        endDate: 'Present',
        bullets: [
          {
            original: 'Built Python FastAPI services handling 2M+ daily requests with PostgreSQL and Redis caching.',
            tailored: 'Designed and implemented scalable RESTful APIs using Python FastAPI, handling 2M+ daily requests with PostgreSQL and Redis caching strategies.',
            changeReason: 'Emphasized API design and framework alignment with JD requirements',
            keywordsAddressed: ['Python', 'FastAPI', 'RESTful APIs', 'PostgreSQL', 'Redis'],
            confidence: 'high',
          },
          {
            original: 'Designed ETL jobs that reduced reporting latency from hours to under 15 minutes.',
            tailored: 'Built reliable data pipelines and ETL jobs that reduced reporting latency from hours to under 15 minutes, optimizing data ingestion workflows.',
            changeReason: 'Aligned with JD responsibility for data pipelines and ingestion',
            keywordsAddressed: ['data pipelines', 'ingestion', 'ETL'],
            confidence: 'high',
          },
          {
            original: 'Collaborated with product and QA to ship features using GitHub Actions CI/CD pipelines.',
            tailored: 'Collaborated with cross-functional teams including frontend, product, and QA to ship features using GitHub Actions CI/CD pipelines, contributing to engineering best practices.',
            changeReason: 'Expanded collaboration description to match JD language',
            keywordsAddressed: ['collaboration', 'CI/CD', 'best practices'],
            confidence: 'medium',
          },
          {
            original: 'Wrote unit and integration tests that increased backend coverage from 58% to 81%.',
            tailored: 'Wrote automated unit and integration tests that increased backend coverage from 58% to 81%, ensuring code quality and reliability.',
            changeReason: 'Added "automated" keyword to match JD testing requirements',
            keywordsAddressed: ['automated testing', 'code quality'],
            confidence: 'high',
          },
        ],
      },
      {
        company: 'BrightCart Labs',
        title: 'Junior Backend Developer',
        startDate: 'Jun 2020',
        endDate: 'Dec 2021',
        bullets: [
          {
            original: 'Implemented REST endpoints in Node.js/Express for an e-commerce admin dashboard.',
            tailored: 'Implemented RESTful API endpoints in Node.js/Express for an e-commerce admin dashboard, following REST best practices.',
            changeReason: 'Added "RESTful" and "best practices" to align with JD',
            keywordsAddressed: ['RESTful APIs', 'best practices'],
            confidence: 'high',
          },
          {
            original: 'Optimized SQL queries and added indexes that improved checkout API response times by 30%.',
            tailored: 'Optimized PostgreSQL queries and schema design with indexes that improved checkout API response times by 30%.',
            changeReason: 'Specified PostgreSQL and added "schema design" to match JD',
            keywordsAddressed: ['PostgreSQL', 'schema design', 'optimization'],
            confidence: 'high',
          },
          {
            original: 'Participated in code reviews and on-call rotation for production incidents.',
            tailored: 'Participated in code reviews, incident response, and on-call rotation for production incidents, contributing to team engineering practices.',
            changeReason: 'Added "incident response" to match JD responsibilities',
            keywordsAddressed: ['code reviews', 'incident response'],
            confidence: 'medium',
          },
        ],
      },
    ],
    tailoredProjects: [
      {
        name: 'Inventory Sync Tool',
        description: 'Created a Python script and scheduled job to reconcile warehouse CSV exports with PostgreSQL inventory tables.',
        bullets: [
          {
            original: 'Developed automated reconciliation process',
            tailored: 'Developed automated data reconciliation process using Python and PostgreSQL for inventory management.',
            changeReason: 'Added "data" and specified technologies',
            keywordsAddressed: ['Python', 'PostgreSQL', 'data'],
            confidence: 'high',
          },
          {
            original: 'Reduced manual inventory errors',
            tailored: 'Reduced manual inventory errors through automated data validation and background job processing.',
            changeReason: 'Expanded to include "background job" to match JD',
            keywordsAddressed: ['background jobs', 'automation'],
            confidence: 'low',
            riskFlag: 'May overstate scope - original was simple validation',
          },
        ],
        technologies: ['Python', 'PostgreSQL', 'CSV'],
      },
    ],
  },
  gapAnalysis: {
    gaps: [
      {
        name: 'FastAPI framework experience',
        importance: 'high',
        jdEvidence: 'Preferred: Experience with FastAPI or similar Python frameworks',
        resumeEvidence: 'Built Python FastAPI services at Northline Analytics',
        suggestedAction: 'Emphasize FastAPI experience in bullet points',
        canSafelyAdd: false,
        category: 'skill',
      },
      {
        name: 'Redis caching strategies',
        importance: 'medium',
        jdEvidence: 'Preferred: Exposure to Redis, message queues, or event-driven architectures',
        resumeEvidence: 'Used Redis caching in FastAPI services',
        suggestedAction: 'Highlight Redis usage in relevant bullets',
        canSafelyAdd: false,
        category: 'tool',
      },
      {
        name: 'AWS cloud deployment',
        importance: 'medium',
        jdEvidence: 'Preferred: AWS or other cloud provider experience',
        resumeEvidence: 'AWS Certified Cloud Practitioner certification',
        suggestedAction: 'Mention AWS certification prominently',
        canSafelyAdd: false,
        category: 'tool',
      },
      {
        name: 'Message queue experience',
        importance: 'low',
        jdEvidence: 'Preferred: Exposure to Redis, message queues, or event-driven architectures',
        resumeEvidence: 'Not explicitly mentioned',
        suggestedAction: 'Consider if any background job work involved message queues',
        canSafelyAdd: false,
        category: 'tool',
      },
    ],
  },
  status: 'complete',
};
